### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mohabedalgani** [XHAL9000/FAKE-NEWS#1]
Hi. The code looks great.. well done.. anyway can you share with me the link of the tweets file. as I can not find it anywhere.

**Comment by XHAL9000** [comment]
Thank you for your interest, I used the AraCov dataset which contains tweets ids of real and fake tweets, and then I used Twitter API to collect the tweets.
AraCov dataset : https://gitlab.com/bigirqu/ArCOV-19
